spring.data.mongodb.uri=mongodb+srv://rajathshetty09:Rockstar9832@cluster0.gxtqw52.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=bikerental
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
logging.level.org.springframework.data.mongodb=INFO
