# Force application to use an in-memory/mock data layer instead of a local MongoDB service
spring.data.mongodb.uri=mongodb+srv://mockUser:mockPass@cluster0.example.mongodb.net/test?retryWrites=true&w=majority
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
